services:
  frontend:
    build: ./frontend/Dockerfile
    ports:
      8501:8501
    restart: always
    # volumes:
    #   - .:/app

  backend:
    build: ./backend/Dockerfile
    ports:
      5000:5000
    restart: always

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  - pg-data:
